// One place for storage photo URLs, used everywhere (cards, gallery, JSON-LD).
// Variants are pre-generated by scripts/process-images.mjs.
// Paths starting with "demo/" are demo-mode photos served from /public.
export const photoUrl = (storagePath: string, width: 400 | 800 | 1600) =>
  storagePath.startsWith("demo/")
    ? `/${storagePath}-${width}.webp`
    : `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/restaurant-photos/${storagePath}-${width}.webp`;
